# Generated by Django 5.1.3 on 2024-11-15 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0004_sitesetup_faveicon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesetup',
            old_name='faveicon',
            new_name='favicon',
        ),
    ]
